version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    groups:
      docker-dependencies:
        patterns:
          - "github.com/docker/cli"
          - "github.com/docker/docker"
    labels:
      - "kind/dependencies"
      - "bot"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    labels:
      - "kind/dependencies"
      - "bot"
