name: docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

env:
  DESTDIR: ./bin
  DOCKER_BUILD_SUMMARY: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to push to gh-pages
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      -
        name: Build docs
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        with:
          source: .
          provenance: false
          targets: docs
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@fa6ac37620bc5d44b93e15caed498629665e9ff5 # v4.2.0
        with:
          pages_threshold: major_outage
      -
        name: Deploy
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4.2.0
        with:
          target_branch: gh-pages
          build_dir: ${{ env.DESTDIR }}/site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
