name: e2e

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
      - 'v*'
  pull_request:

env:
  BUILD_TAG: 'swarm-cronjob:local'
  SERVICE_NAME: 'swarm-cronjob'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      -
        name: Build
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        with:
          source: .
          targets: image-local
      -
        name: Swarm init
        run: |
          docker swarm leave --force > /dev/null 2>&1 || true
          docker swarm init --advertise-addr $(dig +short myip.opendns.com @resolver1.opendns.com)
      -
        name: Swarm deploy stacks
        run: |
          docker stack deploy date -c test/date.yml
          docker stack deploy sleep -c test/sleep.yml
          docker stack deploy error -c test/error.yml
          docker stack deploy configs -c test/configs.yml
          docker stack deploy global -c test/global.yml
          docker stack deploy more_replicas -c test/more_replicas.yml
          docker stack deploy query -c test/query.yml
      -
        name: Create service
        run: |
          docker service create --name ${{ env.SERVICE_NAME }} \
            --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock \
            --env "LOG_LEVEL=debug" \
            --env "LOG_JSON=false" \
            --constraint 'node.role == manager' \
            ${{ env.BUILD_TAG }}
      -
        name: Check service logs
        uses: crazy-max/.github/.github/actions/container-logs-check@c0330b414db4cc26a27bbd6f896af62395634183 # main
        with:
          name: ${{ env.SERVICE_NAME }}
          type: service
          log_check: "Number of cronjob tasks: 7"
          timeout: 120
